const DEFAULT_REGION_ISO_CODE = 'US';

/**
 * Interface defining the structure of a deposit region
 * Contains region information including phone formatting and currency details
 */
export interface DepositRegion {
  isoCode: string;
  flag: string;
  name: string;
  phone: {
    prefix: string;
    placeholder: string;
    template: string;
  };
  currency: string;
  supported: boolean;
  recommended?: boolean;
}

/**
 * Array of all available deposit regions with their configuration
 * Includes both supported and unsupported regions for comprehensive coverage
 */
export const DEPOSIT_REGIONS: DepositRegion[] = [
  {
    isoCode: 'US',
    flag: '🇺🇸',
    name: 'United States of America',
    phone: {
      prefix: '+1',
      placeholder: '(555) 123-4567',
      template: '(XXX) XXX-XXXX',
    },
    currency: 'USD',
    supported: true,
    recommended: true,
  },
  {
    isoCode: 'AT',
    flag: '🇦🇹',
    name: 'Austria',
    phone: {
      prefix: '+43',
      placeholder: '660 1234567',
      template: 'XXX XXXXXXX',
    },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'BE',
    flag: '🇧🇪',
    name: 'Belgium',
    phone: { prefix: '+32', placeholder: '123 45 67', template: 'XXX XX XX' },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'BG',
    flag: '🇧🇬',
    name: 'Bulgaria',
    phone: {
      prefix: '+359',
      placeholder: '87 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'BGN',
    supported: true,
  },
  {
    isoCode: 'HR',
    flag: '🇭🇷',
    name: 'Croatia',
    phone: {
      prefix: '+385',
      placeholder: '91 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'HRK',
    supported: true,
  },
  {
    isoCode: 'CY',
    flag: '🇨🇾',
    name: 'Cyprus',
    phone: { prefix: '+357', placeholder: '96 123456', template: 'XX XXXXXX' },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'CZ',
    flag: '🇨🇿',
    name: 'Czech Republic',
    phone: {
      prefix: '+420',
      placeholder: '601 123 456',
      template: 'XXX XXX XXX',
    },
    currency: 'CZK',
    supported: true,
  },
  {
    isoCode: 'DK',
    flag: '🇩🇰',
    name: 'Denmark',
    phone: {
      prefix: '+45',
      placeholder: '20 12 34 56',
      template: 'XX XX XX XX',
    },
    currency: 'DKK',
    supported: true,
  },
  {
    isoCode: 'EE',
    flag: '🇪🇪',
    name: 'Estonia',
    phone: { prefix: '+372', placeholder: '5123 4567', template: 'XXXX XXXX' },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'FI',
    flag: '🇫🇮',
    name: 'Finland',
    phone: {
      prefix: '+358',
      placeholder: '40 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'FR',
    flag: '🇫🇷',
    name: 'France',
    phone: {
      prefix: '+33',
      placeholder: '6 12 34 56 78',
      template: 'X XX XX XX XX',
    },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'DE',
    flag: '🇩🇪',
    name: 'Germany',
    phone: {
      prefix: '+49',
      placeholder: '1512 3456789',
      template: 'XXXX XXXXXXX',
    },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'GR',
    flag: '🇬🇷',
    name: 'Greece',
    phone: {
      prefix: '+30',
      placeholder: '691 234 5678',
      template: 'XXX XXX XXXX',
    },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'HU',
    flag: '🇭🇺',
    name: 'Hungary',
    phone: {
      prefix: '+36',
      placeholder: '20 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'HUF',
    supported: true,
  },
  {
    isoCode: 'IE',
    flag: '🇮🇪',
    name: 'Ireland',
    phone: {
      prefix: '+353',
      placeholder: '85 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'IT',
    flag: '🇮🇹',
    name: 'Italy',
    phone: {
      prefix: '+39',
      placeholder: '312 345 6789',
      template: 'XXX XXX XXXX',
    },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'LV',
    flag: '🇱🇻',
    name: 'Latvia',
    phone: {
      prefix: '+371',
      placeholder: '21 123 456',
      template: 'XX XXX XXX',
    },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'LT',
    flag: '🇱🇹',
    name: 'Lithuania',
    phone: { prefix: '+370', placeholder: '612 34567', template: 'XXX XXXXX' },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'LU',
    flag: '🇱🇺',
    name: 'Luxembourg',
    phone: {
      prefix: '+352',
      placeholder: '621 123 456',
      template: 'XXX XXX XXX',
    },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'MT',
    flag: '🇲🇹',
    name: 'Malta',
    phone: { prefix: '+356', placeholder: '9912 3456', template: 'XXXX XXXX' },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'NL',
    flag: '🇳🇱',
    name: 'Netherlands',
    phone: { prefix: '+31', placeholder: '6 12345678', template: 'X XXXXXXXX' },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'PL',
    flag: '🇵🇱',
    name: 'Poland',
    phone: {
      prefix: '+48',
      placeholder: '512 345 678',
      template: 'XXX XXX XXX',
    },
    currency: 'PLN',
    supported: true,
  },
  {
    isoCode: 'PT',
    flag: '🇵🇹',
    name: 'Portugal',
    phone: {
      prefix: '+351',
      placeholder: '912 345 678',
      template: 'XXX XXX XXX',
    },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'RO',
    flag: '🇷🇴',
    name: 'Romania',
    phone: {
      prefix: '+40',
      placeholder: '721 234 567',
      template: 'XXX XXX XXX',
    },
    currency: 'RON',
    supported: true,
  },
  {
    isoCode: 'SK',
    flag: '🇸🇰',
    name: 'Slovakia',
    phone: {
      prefix: '+421',
      placeholder: '912 345 678',
      template: 'XXX XXX XXX',
    },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'SI',
    flag: '🇸🇮',
    name: 'Slovenia',
    phone: {
      prefix: '+386',
      placeholder: '31 234 567',
      template: 'XX XXX XXX',
    },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'ES',
    flag: '🇪🇸',
    name: 'Spain',
    phone: {
      prefix: '+34',
      placeholder: '612 34 56 78',
      template: 'XXX XX XX XX',
    },
    currency: 'EUR',
    supported: true,
  },
  {
    isoCode: 'SE',
    flag: '🇸🇪',
    name: 'Sweden',
    phone: {
      prefix: '+46',
      placeholder: '70 123 45 67',
      template: 'XX XXX XX XX',
    },
    currency: 'SEK',
    supported: true,
  },
  // Unsupported countries
  {
    isoCode: 'AF',
    flag: '🇦🇫',
    name: 'Afghanistan',
    phone: {
      prefix: '+93',
      placeholder: '70 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'AFN',
    supported: false,
  },
  {
    isoCode: 'AX',
    flag: '🇦🇽',
    name: 'Åland Islands',
    phone: {
      prefix: '+358',
      placeholder: '123 456 789',
      template: 'XXX XXX XXX',
    },
    currency: 'EUR',
    supported: false,
  },
  {
    isoCode: 'AL',
    flag: '🇦🇱',
    name: 'Albania',
    phone: {
      prefix: '+355',
      placeholder: '66 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'ALL',
    supported: false,
  },
  {
    isoCode: 'DZ',
    flag: '🇩🇿',
    name: 'Algeria',
    phone: {
      prefix: '+213',
      placeholder: '661 23 45 67',
      template: 'XXX XX XX XX',
    },
    currency: 'DZD',
    supported: false,
  },
  {
    isoCode: 'AS',
    flag: '🇦🇸',
    name: 'American Samoa',
    phone: { prefix: '+1 684', placeholder: '733 1234', template: 'XXX XXXX' },
    currency: 'USD',
    supported: false,
  },
  {
    isoCode: 'AD',
    flag: '🇦🇩',
    name: 'Andorra',
    phone: { prefix: '+376', placeholder: '123 456', template: 'XXX XXX' },
    currency: 'EUR',
    supported: false,
  },
  {
    isoCode: 'AO',
    flag: '🇦🇴',
    name: 'Angola',
    phone: {
      prefix: '+244',
      placeholder: '923 123 456',
      template: 'XXX XXX XXX',
    },
    currency: 'AOA',
    supported: false,
  },
  {
    isoCode: 'AI',
    flag: '🇦🇮',
    name: 'Anguilla',
    phone: { prefix: '+1 264', placeholder: '235 1234', template: 'XXX XXXX' },
    currency: 'XCD',
    supported: false,
  },
  {
    isoCode: 'AQ',
    flag: '🇦🇶',
    name: 'Antarctica',
    phone: { prefix: '', placeholder: '', template: '' },
    currency: '',
    supported: false,
  },
  {
    isoCode: 'AG',
    flag: '🇦🇬',
    name: 'Antigua and Barbuda',
    phone: { prefix: '+1 268', placeholder: '464 1234', template: 'XXX XXXX' },
    currency: 'XCD',
    supported: false,
  },
  {
    isoCode: 'AR',
    flag: '🇦🇷',
    name: 'Argentina',
    phone: {
      prefix: '+54',
      placeholder: '9 11 1234 5678',
      template: 'X XX XXXX XXXX',
    },
    currency: 'ARS',
    supported: false,
  },
  {
    isoCode: 'AM',
    flag: '🇦🇲',
    name: 'Armenia',
    phone: { prefix: '+374', placeholder: '77 123456', template: 'XX XXXXXX' },
    currency: 'AMD',
    supported: false,
  },
  {
    isoCode: 'AW',
    flag: '🇦🇼',
    name: 'Aruba',
    phone: { prefix: '+297', placeholder: '560 1234', template: 'XXX XXXX' },
    currency: 'AWG',
    supported: false,
  },
  {
    isoCode: 'AU',
    flag: '🇦🇺',
    name: 'Australia',
    phone: {
      prefix: '+61',
      placeholder: '412 345 678',
      template: 'XXX XXX XXX',
    },
    currency: 'AUD',
    supported: false,
  },
  {
    isoCode: 'AZ',
    flag: '🇦🇿',
    name: 'Azerbaijan',
    phone: {
      prefix: '+994',
      placeholder: '40 123 45 67',
      template: 'XX XXX XX XX',
    },
    currency: 'AZN',
    supported: false,
  },
  {
    isoCode: 'BS',
    flag: '🇧🇸',
    name: 'Bahamas',
    phone: { prefix: '+1 242', placeholder: '359 1234', template: 'XXX XXXX' },
    currency: 'BSD',
    supported: false,
  },
  {
    isoCode: 'BH',
    flag: '🇧🇭',
    name: 'Bahrain',
    phone: { prefix: '+973', placeholder: '3600 1234', template: 'XXXX XXXX' },
    currency: 'BHD',
    supported: false,
  },
  {
    isoCode: 'BD',
    flag: '🇧🇩',
    name: 'Bangladesh',
    phone: {
      prefix: '+880',
      placeholder: '17 1234 5678',
      template: 'XX XXXX XXXX',
    },
    currency: 'BDT',
    supported: false,
  },
  {
    isoCode: 'BB',
    flag: '🇧🇧',
    name: 'Barbados',
    phone: { prefix: '+1 246', placeholder: '250 1234', template: 'XXX XXXX' },
    currency: 'BBD',
    supported: false,
  },
  {
    isoCode: 'BY',
    flag: '🇧🇾',
    name: 'Belarus',
    phone: {
      prefix: '+375',
      placeholder: '29 123 45 67',
      template: 'XX XXX XX XX',
    },
    currency: 'BYN',
    supported: false,
  },
  {
    isoCode: 'BZ',
    flag: '🇧🇿',
    name: 'Belize',
    phone: { prefix: '+501', placeholder: '600 1234', template: 'XXX XXXX' },
    currency: 'BZD',
    supported: false,
  },
  {
    isoCode: 'BJ',
    flag: '🇧🇯',
    name: 'Benin',
    phone: {
      prefix: '+229',
      placeholder: '90 01 23 45',
      template: 'XX XX XX XX',
    },
    currency: 'XOF',
    supported: false,
  },
  {
    isoCode: 'BM',
    flag: '🇧🇲',
    name: 'Bermuda',
    phone: { prefix: '+1 441', placeholder: '234 5678', template: 'XXX XXXX' },
    currency: 'BMD',
    supported: false,
  },
  {
    isoCode: 'BT',
    flag: '🇧🇹',
    name: 'Bhutan',
    phone: {
      prefix: '+975',
      placeholder: '17 123 456',
      template: 'XX XXX XXX',
    },
    currency: 'BTN',
    supported: false,
  },
  {
    isoCode: 'BO',
    flag: '🇧🇴',
    name: 'Bolivia',
    phone: { prefix: '+591', placeholder: '71234567', template: 'XXXXXXXX' },
    currency: 'BOB',
    supported: false,
  },
  {
    isoCode: 'BQ',
    flag: '🇧🇶',
    name: 'Bonaire Sint Eustatius and Saba',
    phone: { prefix: '+599', placeholder: '318 1234', template: 'XXX XXXX' },
    currency: 'USD',
    supported: false,
  },
  {
    isoCode: 'BA',
    flag: '🇧🇦',
    name: 'Bosnia and Herzegovina',
    phone: {
      prefix: '+387',
      placeholder: '61 123 456',
      template: 'XX XXX XXX',
    },
    currency: 'BAM',
    supported: false,
  },
  {
    isoCode: 'BW',
    flag: '🇧🇼',
    name: 'Botswana',
    phone: {
      prefix: '+267',
      placeholder: '71 123 456',
      template: 'XX XXX XXX',
    },
    currency: 'BWP',
    supported: false,
  },
  {
    isoCode: 'BV',
    flag: '🇧🇻',
    name: 'Bouvet Island',
    phone: { prefix: '', placeholder: '', template: '' },
    currency: 'NOK',
    supported: false,
  },
  {
    isoCode: 'BR',
    flag: '🇧🇷',
    name: 'Brazil',
    phone: {
      prefix: '+55',
      placeholder: '11 91234 5678',
      template: 'XX XXXXX XXXX',
    },
    currency: 'BRL',
    supported: false,
  },
  {
    isoCode: 'IO',
    flag: '🇮🇴',
    name: 'British Indian Ocean Territory',
    phone: { prefix: '+246', placeholder: '380 1234', template: 'XXX XXXX' },
    currency: 'USD',
    supported: false,
  },
  {
    isoCode: 'BN',
    flag: '🇧🇳',
    name: 'Brunei Darussalam',
    phone: { prefix: '+673', placeholder: '712 3456', template: 'XXX XXXX' },
    currency: 'BND',
    supported: false,
  },
  {
    isoCode: 'BF',
    flag: '🇧🇫',
    name: 'Burkina Faso',
    phone: {
      prefix: '+226',
      placeholder: '70 12 34 56',
      template: 'XX XX XX XX',
    },
    currency: 'XOF',
    supported: false,
  },
  {
    isoCode: 'BI',
    flag: '🇧🇮',
    name: 'Burundi',
    phone: {
      prefix: '+257',
      placeholder: '79 56 12 34',
      template: 'XX XX XX XX',
    },
    currency: 'BIF',
    supported: false,
  },
  {
    isoCode: 'KH',
    flag: '🇰🇭',
    name: 'Cambodia',
    phone: {
      prefix: '+855',
      placeholder: '12 345 678',
      template: 'XX XXX XXX',
    },
    currency: 'KHR',
    supported: false,
  },
  {
    isoCode: 'CM',
    flag: '🇨🇲',
    name: 'Cameroon',
    phone: {
      prefix: '+237',
      placeholder: '6 71 23 45 67',
      template: 'X XX XX XX XX',
    },
    currency: 'XAF',
    supported: false,
  },
  {
    isoCode: 'CA',
    flag: '🇨🇦',
    name: 'Canada',
    phone: {
      prefix: '+1',
      placeholder: '(416) 123-4567',
      template: '(XXX) XXX-XXXX',
    },
    currency: 'CAD',
    supported: false,
  },
  {
    isoCode: 'CV',
    flag: '🇨🇻',
    name: 'Cape Verde',
    phone: { prefix: '+238', placeholder: '991 12 34', template: 'XXX XX XX' },
    currency: 'CVE',
    supported: false,
  },
  {
    isoCode: 'KY',
    flag: '🇰🇾',
    name: 'Cayman Islands',
    phone: { prefix: '+1 345', placeholder: '916 1234', template: 'XXX XXXX' },
    currency: 'KYD',
    supported: false,
  },
  {
    isoCode: 'CF',
    flag: '🇨🇫',
    name: 'Central African Republic',
    phone: {
      prefix: '+236',
      placeholder: '70 01 23 45',
      template: 'XX XX XX XX',
    },
    currency: 'XAF',
    supported: false,
  },
  {
    isoCode: 'TD',
    flag: '🇹🇩',
    name: 'Chad',
    phone: {
      prefix: '+235',
      placeholder: '63 01 23 45',
      template: 'XX XX XX XX',
    },
    currency: 'XAF',
    supported: false,
  },
  {
    isoCode: 'CL',
    flag: '🇨🇱',
    name: 'Chile',
    phone: {
      prefix: '+56',
      placeholder: '9 1234 5678',
      template: 'X XXXX XXXX',
    },
    currency: 'CLP',
    supported: false,
  },
  {
    isoCode: 'CN',
    flag: '🇨🇳',
    name: 'China',
    phone: {
      prefix: '+86',
      placeholder: '131 2345 6789',
      template: 'XXX XXXX XXXX',
    },
    currency: 'CNY',
    supported: false,
  },
  {
    isoCode: 'CX',
    flag: '🇨🇽',
    name: 'Christmas Island',
    phone: {
      prefix: '+61',
      placeholder: '491 234 567',
      template: 'XXX XXX XXX',
    },
    currency: 'AUD',
    supported: false,
  },
  {
    isoCode: 'CC',
    flag: '🇨🇨',
    name: 'Cocos (Keeling) Islands',
    phone: {
      prefix: '+61',
      placeholder: '891 234 567',
      template: 'XXX XXX XXX',
    },
    currency: 'AUD',
    supported: false,
  },
  {
    isoCode: 'CO',
    flag: '🇨🇴',
    name: 'Colombia',
    phone: {
      prefix: '+57',
      placeholder: '321 1234567',
      template: 'XXX XXXXXXX',
    },
    currency: 'COP',
    supported: false,
  },
  {
    isoCode: 'KM',
    flag: '🇰🇲',
    name: 'Comoros',
    phone: { prefix: '+269', placeholder: '321 23 45', template: 'XXX XX XX' },
    currency: 'KMF',
    supported: false,
  },
  {
    isoCode: 'CG',
    flag: '🇨🇬',
    name: 'Congo',
    phone: {
      prefix: '+242',
      placeholder: '06 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'XAF',
    supported: false,
  },
  {
    isoCode: 'CD',
    flag: '🇨🇩',
    name: 'Democratic Republic of the Congo',
    phone: {
      prefix: '+243',
      placeholder: '99 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'CDF',
    supported: false,
  },
  {
    isoCode: 'CK',
    flag: '🇨🇰',
    name: 'Cook Islands',
    phone: { prefix: '+682', placeholder: '21 234', template: 'XX XXX' },
    currency: 'NZD',
    supported: false,
  },
  {
    isoCode: 'CR',
    flag: '🇨🇷',
    name: 'Costa Rica',
    phone: { prefix: '+506', placeholder: '8312 3456', template: 'XXXX XXXX' },
    currency: 'CRC',
    supported: false,
  },
  {
    isoCode: 'CI',
    flag: '🇨🇮',
    name: "Côte d'Ivoire",
    phone: {
      prefix: '+225',
      placeholder: '01 23 45 67',
      template: 'XX XX XX XX',
    },
    currency: 'XOF',
    supported: false,
  },
  {
    isoCode: 'CW',
    flag: '🇨🇼',
    name: 'Curaçao',
    phone: {
      prefix: '+599',
      placeholder: '9 461 1234',
      template: 'X XXX XXXX',
    },
    currency: 'ANG',
    supported: false,
  },
  {
    isoCode: 'DJ',
    flag: '🇩🇯',
    name: 'Djibouti',
    phone: {
      prefix: '+253',
      placeholder: '77 83 10 01',
      template: 'XX XX XX XX',
    },
    currency: 'DJF',
    supported: false,
  },
  {
    isoCode: 'DM',
    flag: '🇩🇲',
    name: 'Dominica',
    phone: { prefix: '+1 767', placeholder: '225 1234', template: 'XXX XXXX' },
    currency: 'XCD',
    supported: false,
  },
  {
    isoCode: 'DO',
    flag: '🇩🇴',
    name: 'Dominican Republic',
    phone: { prefix: '+1 809', placeholder: '221 1234', template: 'XXX XXXX' },
    currency: 'DOP',
    supported: false,
  },
  {
    isoCode: 'EC',
    flag: '🇪🇨',
    name: 'Ecuador',
    phone: {
      prefix: '+593',
      placeholder: '99 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'USD',
    supported: false,
  },
  {
    isoCode: 'EG',
    flag: '🇪🇬',
    name: 'Egypt',
    phone: {
      prefix: '+20',
      placeholder: '10 1234 5678',
      template: 'XX XXXX XXXX',
    },
    currency: 'EGP',
    supported: false,
  },
  {
    isoCode: 'SV',
    flag: '🇸🇻',
    name: 'El Salvador',
    phone: { prefix: '+503', placeholder: '7012 3456', template: 'XXXX XXXX' },
    currency: 'USD',
    supported: false,
  },
  {
    isoCode: 'GQ',
    flag: '🇬🇶',
    name: 'Equatorial Guinea',
    phone: {
      prefix: '+240',
      placeholder: '222 123 456',
      template: 'XXX XXX XXX',
    },
    currency: 'XAF',
    supported: false,
  },
  {
    isoCode: 'ER',
    flag: '🇪🇷',
    name: 'Eritrea',
    phone: { prefix: '+291', placeholder: '1 712 345', template: 'X XXX XXX' },
    currency: 'ERN',
    supported: false,
  },
  {
    isoCode: 'ET',
    flag: '🇪🇹',
    name: 'Ethiopia',
    phone: {
      prefix: '+251',
      placeholder: '91 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'ETB',
    supported: false,
  },
  {
    isoCode: 'FK',
    flag: '🇫🇰',
    name: 'Falkland Islands (Malvinas)',
    phone: { prefix: '+500', placeholder: '51234', template: 'XXXXX' },
    currency: 'FKP',
    supported: false,
  },
  {
    isoCode: 'FO',
    flag: '🇫🇴',
    name: 'Faroe Islands',
    phone: { prefix: '+298', placeholder: '211234', template: 'XXXXXX' },
    currency: 'DKK',
    supported: false,
  },
  {
    isoCode: 'FJ',
    flag: '🇫🇯',
    name: 'Fiji',
    phone: { prefix: '+679', placeholder: '701 2345', template: 'XXX XXXX' },
    currency: 'FJD',
    supported: false,
  },
  {
    isoCode: 'GF',
    flag: '🇬🇫',
    name: 'French Guiana',
    phone: {
      prefix: '+594',
      placeholder: '694 20 12 34',
      template: 'XXX XX XX XX',
    },
    currency: 'EUR',
    supported: false,
  },
  {
    isoCode: 'PF',
    flag: '🇵🇫',
    name: 'French Polynesia',
    phone: {
      prefix: '+689',
      placeholder: '87 12 34 56',
      template: 'XX XX XX XX',
    },
    currency: 'XPF',
    supported: false,
  },
  {
    isoCode: 'TF',
    flag: '🇹🇫',
    name: 'French Southern Territories',
    phone: { prefix: '', placeholder: '', template: '' },
    currency: 'EUR',
    supported: false,
  },
  {
    isoCode: 'GA',
    flag: '🇬🇦',
    name: 'Gabon',
    phone: {
      prefix: '+241',
      placeholder: '06 12 34 56',
      template: 'XX XX XX XX',
    },
    currency: 'XAF',
    supported: false,
  },
  {
    isoCode: 'GM',
    flag: '🇬🇲',
    name: 'Gambia',
    phone: { prefix: '+220', placeholder: '301 2345', template: 'XXX XXXX' },
    currency: 'GMD',
    supported: false,
  },
  {
    isoCode: 'GE',
    flag: '🇬🇪',
    name: 'Georgia',
    phone: {
      prefix: '+995',
      placeholder: '599 12 34 56',
      template: 'XXX XX XX XX',
    },
    currency: 'GEL',
    supported: false,
  },
  {
    isoCode: 'GH',
    flag: '🇬🇭',
    name: 'Ghana',
    phone: {
      prefix: '+233',
      placeholder: '24 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'GHS',
    supported: false,
  },
  {
    isoCode: 'GI',
    flag: '🇬🇮',
    name: 'Gibraltar',
    phone: { prefix: '+350', placeholder: '54012345', template: 'XXXXXXXX' },
    currency: 'GIP',
    supported: false,
  },
  {
    isoCode: 'GL',
    flag: '🇬🇱',
    name: 'Greenland',
    phone: { prefix: '+299', placeholder: '22 12 34', template: 'XX XX XX' },
    currency: 'DKK',
    supported: false,
  },
  {
    isoCode: 'GD',
    flag: '🇬🇩',
    name: 'Grenada',
    phone: { prefix: '+1 473', placeholder: '403 1234', template: 'XXX XXXX' },
    currency: 'XCD',
    supported: false,
  },
  {
    isoCode: 'GP',
    flag: '🇬🇵',
    name: 'Guadeloupe',
    phone: {
      prefix: '+590',
      placeholder: '690 12 34 56',
      template: 'XXX XX XX XX',
    },
    currency: 'EUR',
    supported: false,
  },
  {
    isoCode: 'GU',
    flag: '🇬🇺',
    name: 'Guam',
    phone: { prefix: '+1 671', placeholder: '300 1234', template: 'XXX XXXX' },
    currency: 'USD',
    supported: false,
  },
  {
    isoCode: 'GT',
    flag: '🇬🇹',
    name: 'Guatemala',
    phone: { prefix: '+502', placeholder: '5123 4567', template: 'XXXX XXXX' },
    currency: 'GTQ',
    supported: false,
  },
  {
    isoCode: 'GG',
    flag: '🇬🇬',
    name: 'Guernsey',
    phone: {
      prefix: '+44',
      placeholder: '1481 123456',
      template: 'XXXX XXXXXX',
    },
    currency: 'GBP',
    supported: false,
  },
  {
    isoCode: 'GN',
    flag: '🇬🇳',
    name: 'Guinea',
    phone: {
      prefix: '+224',
      placeholder: '622 12 34 56',
      template: 'XXX XX XX XX',
    },
    currency: 'GNF',
    supported: false,
  },
  {
    isoCode: 'GW',
    flag: '🇬🇼',
    name: 'Guinea-Bissau',
    phone: {
      prefix: '+245',
      placeholder: '955 012 345',
      template: 'XXX XXX XXX',
    },
    currency: 'XOF',
    supported: false,
  },
  {
    isoCode: 'GY',
    flag: '🇬🇾',
    name: 'Guyana',
    phone: { prefix: '+592', placeholder: '609 1234', template: 'XXX XXXX' },
    currency: 'GYD',
    supported: false,
  },
  {
    isoCode: 'HT',
    flag: '🇭🇹',
    name: 'Haiti',
    phone: {
      prefix: '+509',
      placeholder: '34 12 3456',
      template: 'XX XX XXXX',
    },
    currency: 'HTG',
    supported: false,
  },
  {
    isoCode: 'HM',
    flag: '🇭🇲',
    name: 'Heard Island and McDonald Islands',
    phone: { prefix: '', placeholder: '', template: '' },
    currency: 'AUD',
    supported: false,
  },
  {
    isoCode: 'VA',
    flag: '🇻🇦',
    name: 'Holy See (Vatican City State)',
    phone: { prefix: '+39', placeholder: '06 6982', template: 'XX XXXX' },
    currency: 'EUR',
    supported: false,
  },
  {
    isoCode: 'HN',
    flag: '🇭🇳',
    name: 'Honduras',
    phone: { prefix: '+504', placeholder: '9123 4567', template: 'XXXX XXXX' },
    currency: 'HNL',
    supported: false,
  },
  {
    isoCode: 'HK',
    flag: '🇭🇰',
    name: 'Hong Kong',
    phone: { prefix: '+852', placeholder: '5123 4567', template: 'XXXX XXXX' },
    currency: 'HKD',
    supported: false,
  },
  {
    isoCode: 'IS',
    flag: '🇮🇸',
    name: 'Iceland',
    phone: { prefix: '+354', placeholder: '611 1234', template: 'XXX XXXX' },
    currency: 'ISK',
    supported: false,
  },
  {
    isoCode: 'IN',
    flag: '🇮🇳',
    name: 'India',
    phone: {
      prefix: '+91',
      placeholder: '91234 56789',
      template: 'XXXXX XXXXX',
    },
    currency: 'INR',
    supported: false,
  },
  {
    isoCode: 'ID',
    flag: '🇮🇩',
    name: 'Indonesia',
    phone: {
      prefix: '+62',
      placeholder: '812 3456 7890',
      template: 'XXX XXXX XXXX',
    },
    currency: 'IDR',
    supported: false,
  },
  {
    isoCode: 'IQ',
    flag: '🇮🇶',
    name: 'Iraq',
    phone: {
      prefix: '+964',
      placeholder: '790 123 4567',
      template: 'XXX XXX XXXX',
    },
    currency: 'IQD',
    supported: false,
  },
  {
    isoCode: 'IM',
    flag: '🇮🇲',
    name: 'Isle of Man',
    phone: {
      prefix: '+44',
      placeholder: '1624 123456',
      template: 'XXXX XXXXXX',
    },
    currency: 'GBP',
    supported: false,
  },
  {
    isoCode: 'IL',
    flag: '🇮🇱',
    name: 'Israel',
    phone: {
      prefix: '+972',
      placeholder: '50 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'ILS',
    supported: false,
  },
  {
    isoCode: 'JM',
    flag: '🇯🇲',
    name: 'Jamaica',
    phone: { prefix: '+1 876', placeholder: '210 1234', template: 'XXX XXXX' },
    currency: 'JMD',
    supported: false,
  },
  {
    isoCode: 'JP',
    flag: '🇯🇵',
    name: 'Japan',
    phone: {
      prefix: '+81',
      placeholder: '90 1234 5678',
      template: 'XX XXXX XXXX',
    },
    currency: 'JPY',
    supported: false,
  },
  {
    isoCode: 'JE',
    flag: '🇯🇪',
    name: 'Jersey',
    phone: {
      prefix: '+44',
      placeholder: '1534 123456',
      template: 'XXXX XXXXXX',
    },
    currency: 'GBP',
    supported: false,
  },
  {
    isoCode: 'JO',
    flag: '🇯🇴',
    name: 'Jordan',
    phone: {
      prefix: '+962',
      placeholder: '7 9012 3456',
      template: 'X XXXX XXXX',
    },
    currency: 'JOD',
    supported: false,
  },
  {
    isoCode: 'KZ',
    flag: '🇰🇿',
    name: 'Kazakhstan',
    phone: {
      prefix: '+7',
      placeholder: '701 123 4567',
      template: 'XXX XXX XXXX',
    },
    currency: 'KZT',
    supported: false,
  },
  {
    isoCode: 'KE',
    flag: '🇰🇪',
    name: 'Kenya',
    phone: {
      prefix: '+254',
      placeholder: '712 345678',
      template: 'XXX XXXXXX',
    },
    currency: 'KES',
    supported: false,
  },
  {
    isoCode: 'KI',
    flag: '🇰🇮',
    name: 'Kiribati',
    phone: { prefix: '+686', placeholder: '72012345', template: 'XXXXXXXX' },
    currency: 'AUD',
    supported: false,
  },
  {
    isoCode: 'KR',
    flag: '🇰🇷',
    name: 'Republic of Korea',
    phone: {
      prefix: '+82',
      placeholder: '10 1234 5678',
      template: 'XX XXXX XXXX',
    },
    currency: 'KRW',
    supported: false,
  },
  {
    isoCode: 'KW',
    flag: '🇰🇼',
    name: 'Kuwait',
    phone: { prefix: '+965', placeholder: '500 12345', template: 'XXX XXXXX' },
    currency: 'KWD',
    supported: false,
  },
  {
    isoCode: 'KG',
    flag: '🇰🇬',
    name: 'Kyrgyzstan',
    phone: {
      prefix: '+996',
      placeholder: '700 123 456',
      template: 'XXX XXX XXX',
    },
    currency: 'KGS',
    supported: false,
  },
  {
    isoCode: 'LA',
    flag: '🇱🇦',
    name: "Lao People's Democratic Republic",
    phone: {
      prefix: '+856',
      placeholder: '20 1234 5678',
      template: 'XX XXXX XXXX',
    },
    currency: 'LAK',
    supported: false,
  },
  {
    isoCode: 'LB',
    flag: '🇱🇧',
    name: 'Lebanon',
    phone: { prefix: '+961', placeholder: '3 123 456', template: 'X XXX XXX' },
    currency: 'LBP',
    supported: false,
  },
  {
    isoCode: 'LS',
    flag: '🇱🇸',
    name: 'Lesotho',
    phone: { prefix: '+266', placeholder: '5012 3456', template: 'XXXX XXXX' },
    currency: 'LSL',
    supported: false,
  },
  {
    isoCode: 'LR',
    flag: '🇱🇷',
    name: 'Liberia',
    phone: {
      prefix: '+231',
      placeholder: '77 012 345',
      template: 'XX XXX XXX',
    },
    currency: 'LRD',
    supported: false,
  },
  {
    isoCode: 'LY',
    flag: '🇱🇾',
    name: 'Libya',
    phone: {
      prefix: '+218',
      placeholder: '91 234 5678',
      template: 'XX XXX XXXX',
    },
    currency: 'LYD',
    supported: false,
  },
  {
    isoCode: 'LI',
    flag: '🇱🇮',
    name: 'Liechtenstein',
    phone: { prefix: '+423', placeholder: '660 1234', template: 'XXX XXXX' },
    currency: 'CHF',
    supported: false,
  },
  {
    isoCode: 'MG',
    flag: '🇲🇬',
    name: 'Madagascar',
    phone: {
      prefix: '+261',
      placeholder: '32 12 345 67',
      template: 'XX XX XXX XX',
    },
    currency: 'MGA',
    supported: false,
  },
  {
    isoCode: 'MW',
    flag: '🇲🇼',
    name: 'Malawi',
    phone: {
      prefix: '+265',
      placeholder: '991 234 567',
      template: 'XXX XXX XXX',
    },
    currency: 'MWK',
    supported: false,
  },
  {
    isoCode: 'MY',
    flag: '🇲🇾',
    name: 'Malaysia',
    phone: {
      prefix: '+60',
      placeholder: '12 345 6789',
      template: 'XX XXX XXXX',
    },
    currency: 'MYR',
    supported: false,
  },
  {
    isoCode: 'MV',
    flag: '🇲🇻',
    name: 'Maldives',
    phone: { prefix: '+960', placeholder: '771 2345', template: 'XXX XXXX' },
    currency: 'MVR',
    supported: false,
  },
  {
    isoCode: 'ML',
    flag: '🇲🇱',
    name: 'Mali',
    phone: {
      prefix: '+223',
      placeholder: '65 01 23 45',
      template: 'XX XX XX XX',
    },
    currency: 'XOF',
    supported: false,
  },
  {
    isoCode: 'MH',
    flag: '🇲🇭',
    name: 'Marshall Islands',
    phone: { prefix: '+692', placeholder: '235 1234', template: 'XXX XXXX' },
    currency: 'USD',
    supported: false,
  },
  {
    isoCode: 'MQ',
    flag: '🇲🇶',
    name: 'Martinique',
    phone: {
      prefix: '+596',
      placeholder: '696 12 34 56',
      template: 'XXX XX XX XX',
    },
    currency: 'EUR',
    supported: false,
  },
  {
    isoCode: 'MR',
    flag: '🇲🇷',
    name: 'Mauritania',
    phone: {
      prefix: '+222',
      placeholder: '22 12 34 56',
      template: 'XX XX XX XX',
    },
    currency: 'MRU',
    supported: false,
  },
  {
    isoCode: 'MU',
    flag: '🇲🇺',
    name: 'Mauritius',
    phone: { prefix: '+230', placeholder: '5251 2345', template: 'XXXX XXXX' },
    currency: 'MUR',
    supported: false,
  },
  {
    isoCode: 'YT',
    flag: '🇾🇹',
    name: 'Mayotte',
    phone: {
      prefix: '+262',
      placeholder: '639 12 34 56',
      template: 'XXX XX XX XX',
    },
    currency: 'EUR',
    supported: false,
  },
  {
    isoCode: 'MX',
    flag: '🇲🇽',
    name: 'Mexico',
    phone: {
      prefix: '+52',
      placeholder: '55 1234 5678',
      template: 'XX XXXX XXXX',
    },
    currency: 'MXN',
    supported: false,
  },
  {
    isoCode: 'FM',
    flag: '🇫🇲',
    name: 'Micronesia',
    phone: { prefix: '+691', placeholder: '350 1234', template: 'XXX XXXX' },
    currency: 'USD',
    supported: false,
  },
  {
    isoCode: 'MD',
    flag: '🇲🇩',
    name: 'Moldova',
    phone: {
      prefix: '+373',
      placeholder: '79 123 456',
      template: 'XX XXX XXX',
    },
    currency: 'MDL',
    supported: false,
  },
  {
    isoCode: 'MC',
    flag: '🇲🇨',
    name: 'Monaco',
    phone: {
      prefix: '+377',
      placeholder: '6 12 34 56 78',
      template: 'X XX XX XX XX',
    },
    currency: 'EUR',
    supported: false,
  },
  {
    isoCode: 'MN',
    flag: '🇲🇳',
    name: 'Mongolia',
    phone: { prefix: '+976', placeholder: '8812 3456', template: 'XXXX XXXX' },
    currency: 'MNT',
    supported: false,
  },
  {
    isoCode: 'ME',
    flag: '🇲🇪',
    name: 'Montenegro',
    phone: {
      prefix: '+382',
      placeholder: '67 123 456',
      template: 'XX XXX XXX',
    },
    currency: 'EUR',
    supported: false,
  },
  {
    isoCode: 'MS',
    flag: '🇲🇸',
    name: 'Montserrat',
    phone: { prefix: '+1 664', placeholder: '492 3456', template: 'XXX XXXX' },
    currency: 'XCD',
    supported: false,
  },
  {
    isoCode: 'MA',
    flag: '🇲🇦',
    name: 'Morocco',
    phone: {
      prefix: '+212',
      placeholder: '661 23 45 67',
      template: 'XXX XX XX XX',
    },
    currency: 'MAD',
    supported: false,
  },
  {
    isoCode: 'MZ',
    flag: '🇲🇿',
    name: 'Mozambique',
    phone: {
      prefix: '+258',
      placeholder: '82 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'MZN',
    supported: false,
  },
  {
    isoCode: 'MM',
    flag: '🇲🇲',
    name: 'Myanmar',
    phone: {
      prefix: '+95',
      placeholder: '9 123 456789',
      template: 'X XXX XXXXXX',
    },
    currency: 'MMK',
    supported: false,
  },
  {
    isoCode: 'NA',
    flag: '🇳🇦',
    name: 'Namibia',
    phone: {
      prefix: '+264',
      placeholder: '81 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'NAD',
    supported: false,
  },
  {
    isoCode: 'NR',
    flag: '🇳🇷',
    name: 'Nauru',
    phone: { prefix: '+674', placeholder: '555 1234', template: 'XXX XXXX' },
    currency: 'AUD',
    supported: false,
  },
  {
    isoCode: 'NP',
    flag: '🇳🇵',
    name: 'Nepal',
    phone: {
      prefix: '+977',
      placeholder: '981 1234567',
      template: 'XXX XXXXXXX',
    },
    currency: 'NPR',
    supported: false,
  },
  {
    isoCode: 'NC',
    flag: '🇳🇨',
    name: 'New Caledonia',
    phone: { prefix: '+687', placeholder: '75 12 34', template: 'XX XX XX' },
    currency: 'XPF',
    supported: false,
  },
  {
    isoCode: 'NZ',
    flag: '🇳🇿',
    name: 'New Zealand',
    phone: {
      prefix: '+64',
      placeholder: '21 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'NZD',
    supported: false,
  },
  {
    isoCode: 'NI',
    flag: '🇳🇮',
    name: 'Nicaragua',
    phone: { prefix: '+505', placeholder: '8123 4567', template: 'XXXX XXXX' },
    currency: 'NIO',
    supported: false,
  },
  {
    isoCode: 'NE',
    flag: '🇳🇪',
    name: 'Niger',
    phone: {
      prefix: '+227',
      placeholder: '93 12 34 56',
      template: 'XX XX XX XX',
    },
    currency: 'XOF',
    supported: false,
  },
  {
    isoCode: 'NG',
    flag: '🇳🇬',
    name: 'Nigeria',
    phone: {
      prefix: '+234',
      placeholder: '803 123 4567',
      template: 'XXX XXX XXXX',
    },
    currency: 'NGN',
    supported: false,
  },
  {
    isoCode: 'NU',
    flag: '🇳🇺',
    name: 'Niue',
    phone: { prefix: '+683', placeholder: '4000', template: 'XXXX' },
    currency: 'NZD',
    supported: false,
  },
  {
    isoCode: 'NF',
    flag: '🇳🇫',
    name: 'Norfolk Island',
    phone: { prefix: '+672', placeholder: '3 2222', template: 'X XXXX' },
    currency: 'AUD',
    supported: false,
  },
  {
    isoCode: 'MP',
    flag: '🇲🇵',
    name: 'Northern Mariana Islands',
    phone: { prefix: '+1 670', placeholder: '234 5678', template: 'XXX XXXX' },
    currency: 'USD',
    supported: false,
  },
  {
    isoCode: 'NO',
    flag: '🇳🇴',
    name: 'Norway',
    phone: { prefix: '+47', placeholder: '412 34 567', template: 'XXX XX XXX' },
    currency: 'NOK',
    supported: false,
  },
  {
    isoCode: 'OM',
    flag: '🇴🇲',
    name: 'Oman',
    phone: { prefix: '+968', placeholder: '9212 3456', template: 'XXXX XXXX' },
    currency: 'OMR',
    supported: false,
  },
  {
    isoCode: 'PK',
    flag: '🇵🇰',
    name: 'Pakistan',
    phone: {
      prefix: '+92',
      placeholder: '300 1234567',
      template: 'XXX XXXXXXX',
    },
    currency: 'PKR',
    supported: false,
  },
  {
    isoCode: 'PW',
    flag: '🇵🇼',
    name: 'Palau',
    phone: { prefix: '+680', placeholder: '488 1234', template: 'XXX XXXX' },
    currency: 'USD',
    supported: false,
  },
  {
    isoCode: 'PS',
    flag: '🇵🇸',
    name: 'State of Palestine',
    phone: {
      prefix: '+970',
      placeholder: '599 123 456',
      template: 'XXX XXX XXX',
    },
    currency: 'ILS',
    supported: false,
  },
  {
    isoCode: 'PA',
    flag: '🇵🇦',
    name: 'Panama',
    phone: { prefix: '+507', placeholder: '6123 4567', template: 'XXXX XXXX' },
    currency: 'PAB',
    supported: false,
  },
  {
    isoCode: 'PG',
    flag: '🇵🇬',
    name: 'Papua New Guinea',
    phone: { prefix: '+675', placeholder: '6812 3456', template: 'XXXX XXXX' },
    currency: 'PGK',
    supported: false,
  },
  {
    isoCode: 'PY',
    flag: '🇵🇾',
    name: 'Paraguay',
    phone: {
      prefix: '+595',
      placeholder: '961 123456',
      template: 'XXX XXXXXX',
    },
    currency: 'PYG',
    supported: false,
  },
  {
    isoCode: 'PE',
    flag: '🇵🇪',
    name: 'Peru',
    phone: {
      prefix: '+51',
      placeholder: '912 345 678',
      template: 'XXX XXX XXX',
    },
    currency: 'PEN',
    supported: false,
  },
  {
    isoCode: 'PH',
    flag: '🇵🇭',
    name: 'Philippines',
    phone: {
      prefix: '+63',
      placeholder: '917 123 4567',
      template: 'XXX XXX XXXX',
    },
    currency: 'PHP',
    supported: false,
  },
  {
    isoCode: 'PN',
    flag: '🇵🇳',
    name: 'Pitcairn',
    phone: { prefix: '+64', placeholder: '9 123 4567', template: 'X XXX XXXX' },
    currency: 'NZD',
    supported: false,
  },
  {
    isoCode: 'PR',
    flag: '🇵🇷',
    name: 'Puerto Rico',
    phone: { prefix: '+1 787', placeholder: '234 5678', template: 'XXX XXXX' },
    currency: 'USD',
    supported: false,
  },
  {
    isoCode: 'QA',
    flag: '🇶🇦',
    name: 'Qatar',
    phone: { prefix: '+974', placeholder: '3312 3456', template: 'XXXX XXXX' },
    currency: 'QAR',
    supported: false,
  },
  {
    isoCode: 'RE',
    flag: '🇷🇪',
    name: 'Réunion',
    phone: {
      prefix: '+262',
      placeholder: '692 12 34 56',
      template: 'XXX XX XX XX',
    },
    currency: 'EUR',
    supported: false,
  },
  {
    isoCode: 'RU',
    flag: '🇷🇺',
    name: 'Russia',
    phone: {
      prefix: '+7',
      placeholder: '912 345 67 89',
      template: 'XXX XXX XX XX',
    },
    currency: 'RUB',
    supported: false,
  },
  {
    isoCode: 'RW',
    flag: '🇷🇼',
    name: 'Rwanda',
    phone: {
      prefix: '+250',
      placeholder: '788 123 456',
      template: 'XXX XXX XXX',
    },
    currency: 'RWF',
    supported: false,
  },
  {
    isoCode: 'BL',
    flag: '🇧🇱',
    name: 'Saint Barthélemy',
    phone: {
      prefix: '+590',
      placeholder: '690 12 34 56',
      template: 'XXX XX XX XX',
    },
    currency: 'EUR',
    supported: false,
  },
  {
    isoCode: 'SH',
    flag: '🇸🇭',
    name: 'Saint Helena Ascension and Tristan da Cunha',
    phone: { prefix: '+290', placeholder: '51234', template: 'XXXXX' },
    currency: 'SHP',
    supported: false,
  },
  {
    isoCode: 'KN',
    flag: '🇰🇳',
    name: 'Saint Kitts and Nevis',
    phone: { prefix: '+1 869', placeholder: '765 1234', template: 'XXX XXXX' },
    currency: 'XCD',
    supported: false,
  },
  {
    isoCode: 'LC',
    flag: '🇱🇨',
    name: 'Saint Lucia',
    phone: { prefix: '+1 758', placeholder: '284 1234', template: 'XXX XXXX' },
    currency: 'XCD',
    supported: false,
  },
  {
    isoCode: 'MF',
    flag: '🇲🇫',
    name: 'Saint Martin (French part)',
    phone: {
      prefix: '+590',
      placeholder: '690 12 34 56',
      template: 'XXX XX XX XX',
    },
    currency: 'EUR',
    supported: false,
  },
  {
    isoCode: 'PM',
    flag: '🇵🇲',
    name: 'Saint Pierre and Miquelon',
    phone: { prefix: '+508', placeholder: '41 23 45', template: 'XX XX XX' },
    currency: 'EUR',
    supported: false,
  },
  {
    isoCode: 'VC',
    flag: '🇻🇨',
    name: 'Saint Vincent and the Grenadines',
    phone: { prefix: '+1 784', placeholder: '430 1234', template: 'XXX XXXX' },
    currency: 'XCD',
    supported: false,
  },
  {
    isoCode: 'WS',
    flag: '🇼🇸',
    name: 'Samoa',
    phone: { prefix: '+685', placeholder: '721 2345', template: 'XXX XXXX' },
    currency: 'WST',
    supported: false,
  },
  {
    isoCode: 'SM',
    flag: '🇸🇲',
    name: 'San Marino',
    phone: {
      prefix: '+378',
      placeholder: '66 123 456',
      template: 'XX XXX XXX',
    },
    currency: 'EUR',
    supported: false,
  },
  {
    isoCode: 'ST',
    flag: '🇸🇹',
    name: 'Sao Tome and Principe',
    phone: { prefix: '+239', placeholder: '990 1234', template: 'XXX XXXX' },
    currency: 'STN',
    supported: false,
  },
  {
    isoCode: 'SA',
    flag: '🇸🇦',
    name: 'Saudi Arabia',
    phone: {
      prefix: '+966',
      placeholder: '50 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'SAR',
    supported: false,
  },
  {
    isoCode: 'SN',
    flag: '🇸🇳',
    name: 'Senegal',
    phone: {
      prefix: '+221',
      placeholder: '77 123 45 67',
      template: 'XX XXX XX XX',
    },
    currency: 'XOF',
    supported: false,
  },
  {
    isoCode: 'RS',
    flag: '🇷🇸',
    name: 'Serbia',
    phone: {
      prefix: '+381',
      placeholder: '60 1234567',
      template: 'XX XXXXXXX',
    },
    currency: 'RSD',
    supported: false,
  },
  {
    isoCode: 'SC',
    flag: '🇸🇨',
    name: 'Seychelles',
    phone: { prefix: '+248', placeholder: '2 510 123', template: 'X XXX XXX' },
    currency: 'SCR',
    supported: false,
  },
  {
    isoCode: 'SL',
    flag: '🇸🇱',
    name: 'Sierra Leone',
    phone: { prefix: '+232', placeholder: '76 123456', template: 'XX XXXXXX' },
    currency: 'SLL',
    supported: false,
  },
  {
    isoCode: 'SG',
    flag: '🇸🇬',
    name: 'Singapore',
    phone: { prefix: '+65', placeholder: '8123 4567', template: 'XXXX XXXX' },
    currency: 'SGD',
    supported: false,
  },
  {
    isoCode: 'SX',
    flag: '🇸🇽',
    name: 'Sint Maarten (Dutch part)',
    phone: { prefix: '+1 721', placeholder: '520 5678', template: 'XXX XXXX' },
    currency: 'ANG',
    supported: false,
  },
  {
    isoCode: 'SB',
    flag: '🇸🇧',
    name: 'Solomon Islands',
    phone: { prefix: '+677', placeholder: '74 12345', template: 'XX XXXXX' },
    currency: 'SBD',
    supported: false,
  },
  {
    isoCode: 'SO',
    flag: '🇸🇴',
    name: 'Somalia',
    phone: {
      prefix: '+252',
      placeholder: '61 1234567',
      template: 'XX XXXXXXX',
    },
    currency: 'SOS',
    supported: false,
  },
  {
    isoCode: 'ZA',
    flag: '🇿🇦',
    name: 'South Africa',
    phone: {
      prefix: '+27',
      placeholder: '82 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'ZAR',
    supported: false,
  },
  {
    isoCode: 'GS',
    flag: '🇬🇸',
    name: 'South Georgia and the South Sandwich Islands',
    phone: { prefix: '', placeholder: '', template: '' },
    currency: 'GBP',
    supported: false,
  },
  {
    isoCode: 'SS',
    flag: '🇸🇸',
    name: 'South Sudan',
    phone: {
      prefix: '+211',
      placeholder: '91 234 5678',
      template: 'XX XXX XXXX',
    },
    currency: 'SSP',
    supported: false,
  },
  {
    isoCode: 'LK',
    flag: '🇱🇰',
    name: 'Sri Lanka',
    phone: {
      prefix: '+94',
      placeholder: '71 234 5678',
      template: 'XX XXX XXXX',
    },
    currency: 'LKR',
    supported: false,
  },
  {
    isoCode: 'SD',
    flag: '🇸🇩',
    name: 'Sudan',
    phone: {
      prefix: '+249',
      placeholder: '91 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'SDG',
    supported: false,
  },
  {
    isoCode: 'SR',
    flag: '🇸🇷',
    name: 'Suriname',
    phone: { prefix: '+597', placeholder: '741 2345', template: 'XXX XXXX' },
    currency: 'SRD',
    supported: false,
  },
  {
    isoCode: 'SJ',
    flag: '🇸🇯',
    name: 'Svalbard and Jan Mayen',
    phone: { prefix: '+47', placeholder: '412 34 567', template: 'XXX XX XXX' },
    currency: 'NOK',
    supported: false,
  },
  {
    isoCode: 'SZ',
    flag: '🇸🇿',
    name: 'Swaziland',
    phone: { prefix: '+268', placeholder: '7612 3456', template: 'XXXX XXXX' },
    currency: 'SZL',
    supported: false,
  },
  {
    isoCode: 'CH',
    flag: '🇨🇭',
    name: 'Switzerland',
    phone: {
      prefix: '+41',
      placeholder: '79 123 45 67',
      template: 'XX XXX XX XX',
    },
    currency: 'CHF',
    supported: false,
  },
  {
    isoCode: 'TW',
    flag: '🇹🇼',
    name: 'Republic of China, Taiwan',
    phone: {
      prefix: '+886',
      placeholder: '912 345 678',
      template: 'XXX XXX XXX',
    },
    currency: 'TWD',
    supported: false,
  },
  {
    isoCode: 'TJ',
    flag: '🇹🇯',
    name: 'Tajikistan',
    phone: {
      prefix: '+992',
      placeholder: '918 12 34 56',
      template: 'XXX XX XX XX',
    },
    currency: 'TJS',
    supported: false,
  },
  {
    isoCode: 'TZ',
    flag: '🇹🇿',
    name: 'United Republic of Tanzania',
    phone: {
      prefix: '+255',
      placeholder: '71 234 5678',
      template: 'XX XXX XXXX',
    },
    currency: 'TZS',
    supported: false,
  },
  {
    isoCode: 'TH',
    flag: '🇹🇭',
    name: 'Thailand',
    phone: {
      prefix: '+66',
      placeholder: '81 234 5678',
      template: 'XX XXX XXXX',
    },
    currency: 'THB',
    supported: false,
  },
  {
    isoCode: 'TL',
    flag: '🇹🇱',
    name: 'Timor-Leste',
    phone: { prefix: '+670', placeholder: '772 12345', template: 'XXX XXXXX' },
    currency: 'USD',
    supported: false,
  },
  {
    isoCode: 'TG',
    flag: '🇹🇬',
    name: 'Togo',
    phone: {
      prefix: '+228',
      placeholder: '90 12 34 56',
      template: 'XX XX XX XX',
    },
    currency: 'XOF',
    supported: false,
  },
  {
    isoCode: 'TK',
    flag: '🇹🇰',
    name: 'Tokelau',
    phone: { prefix: '+690', placeholder: '1234', template: 'XXXX' },
    currency: 'NZD',
    supported: false,
  },
  {
    isoCode: 'TO',
    flag: '🇹🇴',
    name: 'Tonga',
    phone: { prefix: '+676', placeholder: '771 2345', template: 'XXX XXXX' },
    currency: 'TOP',
    supported: false,
  },
  {
    isoCode: 'TT',
    flag: '🇹🇹',
    name: 'Trinidad and Tobago',
    phone: { prefix: '+1 868', placeholder: '291 1234', template: 'XXX XXXX' },
    currency: 'TTD',
    supported: false,
  },
  {
    isoCode: 'TN',
    flag: '🇹🇳',
    name: 'Tunisia',
    phone: {
      prefix: '+216',
      placeholder: '20 123 456',
      template: 'XX XXX XXX',
    },
    currency: 'TND',
    supported: false,
  },
  {
    isoCode: 'TR',
    flag: '🇹🇷',
    name: 'Turkey',
    phone: {
      prefix: '+90',
      placeholder: '532 123 4567',
      template: 'XXX XXX XXXX',
    },
    currency: 'TRY',
    supported: false,
  },
  {
    isoCode: 'TM',
    flag: '🇹🇲',
    name: 'Turkmenistan',
    phone: { prefix: '+993', placeholder: '61 123456', template: 'XX XXXXXX' },
    currency: 'TMT',
    supported: false,
  },
  {
    isoCode: 'TC',
    flag: '🇹🇨',
    name: 'Turks and Caicos Islands',
    phone: { prefix: '+1 649', placeholder: '231 1234', template: 'XXX XXXX' },
    currency: 'USD',
    supported: false,
  },
  {
    isoCode: 'TV',
    flag: '🇹🇻',
    name: 'Tuvalu',
    phone: { prefix: '+688', placeholder: '90123', template: 'XXXXX' },
    currency: 'AUD',
    supported: false,
  },
  {
    isoCode: 'UG',
    flag: '🇺🇬',
    name: 'Uganda',
    phone: {
      prefix: '+256',
      placeholder: '712 345 678',
      template: 'XXX XXX XXX',
    },
    currency: 'UGX',
    supported: false,
  },
  {
    isoCode: 'UA',
    flag: '🇺🇦',
    name: 'Ukraine',
    phone: {
      prefix: '+380',
      placeholder: '67 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'UAH',
    supported: false,
  },
  {
    isoCode: 'AE',
    flag: '🇦🇪',
    name: 'United Arab Emirates',
    phone: {
      prefix: '+971',
      placeholder: '50 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'AED',
    supported: false,
  },
  {
    isoCode: 'GB',
    flag: '🇬🇧',
    name: 'United Kingdom',
    phone: {
      prefix: '+44',
      placeholder: '7700 900123',
      template: 'XXXX XXXXXX',
    },
    currency: 'GBP',
    supported: false,
  },
  {
    isoCode: 'UM',
    flag: '🇺🇲',
    name: 'United States Minor Outlying Islands',
    phone: { prefix: '', placeholder: '', template: '' },
    currency: 'USD',
    supported: false,
  },
  {
    isoCode: 'UY',
    flag: '🇺🇾',
    name: 'Uruguay',
    phone: {
      prefix: '+598',
      placeholder: '99 123 456',
      template: 'XX XXX XXX',
    },
    currency: 'UYU',
    supported: false,
  },
  {
    isoCode: 'UZ',
    flag: '🇺🇿',
    name: 'Uzbekistan',
    phone: {
      prefix: '+998',
      placeholder: '90 123 45 67',
      template: 'XX XXX XX XX',
    },
    currency: 'UZS',
    supported: false,
  },
  {
    isoCode: 'VU',
    flag: '🇻🇺',
    name: 'Vanuatu',
    phone: { prefix: '+678', placeholder: '591 2345', template: 'XXX XXXX' },
    currency: 'VUV',
    supported: false,
  },
  {
    isoCode: 'VE',
    flag: '🇻🇪',
    name: 'Bolivarian Republic of Venezuela',
    phone: {
      prefix: '+58',
      placeholder: '412 123 4567',
      template: 'XXX XXX XXXX',
    },
    currency: 'VES',
    supported: false,
  },
  {
    isoCode: 'VN',
    flag: '🇻🇳',
    name: 'Viet Nam',
    phone: {
      prefix: '+84',
      placeholder: '91 234 5678',
      template: 'XX XXX XXXX',
    },
    currency: 'VND',
    supported: false,
  },
  {
    isoCode: 'VG',
    flag: '🇻🇬',
    name: 'Virgin Islands British',
    phone: { prefix: '+1 284', placeholder: '300 1234', template: 'XXX XXXX' },
    currency: 'USD',
    supported: false,
  },
  {
    isoCode: 'VI',
    flag: '🇻🇮',
    name: 'Virgin Islands U.S.',
    phone: { prefix: '+1 340', placeholder: '300 1234', template: 'XXX XXXX' },
    currency: 'USD',
    supported: false,
  },
  {
    isoCode: 'WF',
    flag: '🇼🇫',
    name: 'Wallis and Futuna',
    phone: { prefix: '+681', placeholder: '50 12 34', template: 'XX XX XX' },
    currency: 'XPF',
    supported: false,
  },
  {
    isoCode: 'EH',
    flag: '🇪🇭',
    name: 'Western Sahara',
    phone: {
      prefix: '+212',
      placeholder: '661 23 45 67',
      template: 'XXX XX XX XX',
    },
    currency: 'MAD',
    supported: false,
  },
  {
    isoCode: 'YE',
    flag: '🇾🇪',
    name: 'Yemen',
    phone: {
      prefix: '+967',
      placeholder: '712 345 678',
      template: 'XXX XXX XXX',
    },
    currency: 'YER',
    supported: false,
  },
  {
    isoCode: 'ZM',
    flag: '🇿🇲',
    name: 'Zambia',
    phone: {
      prefix: '+260',
      placeholder: '95 123 4567',
      template: 'XX XXX XXXX',
    },
    currency: 'ZMW',
    supported: false,
  },
  {
    isoCode: 'ZW',
    flag: '🇿🇼',
    name: 'Zimbabwe',
    phone: {
      prefix: '+263',
      placeholder: '71 234 5678',
      template: 'XX XXX XXXX',
    },
    currency: 'ZWL',
    supported: false,
  },
];

/**
 * Array of US states with their codes and names
 * Used for address validation and state selection in deposit forms
 */
export const US_STATES = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
  { code: 'DC', name: 'District of Columbia' },
  { code: 'AS', name: 'American Samoa' },
  { code: 'GU', name: 'Guam' },
  { code: 'MP', name: 'Northern Mariana Islands' },
  { code: 'PR', name: 'Puerto Rico' },
  { code: 'VI', name: 'U.S. Virgin Islands' },
];

/**
 * Default region configuration for deposit operations
 * Falls back to US region as the default selection
 */
export const DEFAULT_REGION = DEPOSIT_REGIONS.find(
  (region) => region.isoCode === DEFAULT_REGION_ISO_CODE,
) as DepositRegion;
